### ISSUE TITLE
add support for neovim?

### ISSUE THREAD

**Issue by jkunlin** [sc0ty/gdb-vimview#1]
I love this plugin, but could this be used in neovim?

'neo-remote' will add back the '--remote' family of options into noevim, see https://github.com/mhinz/neovim-remote

**Comment by sc0ty** [comment]
You could change vim to whatever you like in VimView.setServerName (vimview.py line 76).
I think I'll made it configurable when I find some time.

**Comment by jkunlin** [comment]
Nice, it works!

**Comment by jkunlin** [comment]
Nice, it works!

**Comment by sc0ty** [comment]
Added option vimview-command, try:
set vimview-command neo-remote
